version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=lambda,s3,dynamodb,apigateway,ses,cognito-idp
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=localstack_default
      - DOCKER_FLAGS=--platform=linux/amd64
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./backend/scripts:/etc/localstack/init/ready.d"
    networks:
      - localstack

networks:
  localstack:
    driver: bridge